export const category = [
  {
    id: 1,
    categoria: {
      1: "Issuance and Refund",
      2: "Emisión y reembolso",
      3: "发行和退款",
      4: "Выпуск и возврат",
      5: "الإصدار والاسترداد",
      6: "Chiqanapaqmi, qillqanapaqmi",
      7: "発行と払い戻し",
      8: "Emissão e reembolso",
      9: "Émission et remboursement",
      10: "발행 및 환불",
    },
    respuesta: {
      1: "Answer 1",
      2: "Respuesta 1",
      3: "答案1",
      4: "ответ 1",
      5: "إجابة 1",
      6: "1 qanqa, jawqanqa",
      7: "回答1",
      8: "resposta 1",
      9: "réponse 1",
      10: "답변 1",
    },
  },
  {
    id: 2,
    categoria: {
      1: "Pre-sale",
      2: "Preventa",
      3: "预售",
      4: "Предпродажа",
      5: "البيع المسبق",
      6: "Qillqanapaqmi",
      7: "プリセール",
      8: "Pré-venda",
      9: "Prévente",
      10: "사전 판매",
    },
    respuesta: {
      1: "Answer 1 for pre-sale",
      2: "Respuesta 1 para preventa",
      3: "预售答案1",
      4: "ответ 1 для предпродажи",
      5: "إجابة 1 للبيع المسبق",
      6: "1 qanqa, jawqanqa pre-sale",
      7: "プリセールの回答1",
      8: "resposta 1 para pré-venda",
      9: "réponse 1 pour la prévente",
      10: "사전 판매를위한 답변 1",
    },
  },
  {
    id: 3,
    categoria: {
      1: "Service Inquiry",
      2: "Consulta de servicios",
      3: "服务咨询",
      4: "Консультация по услугам",
      5: "استشارة الخدمة",
      6: "Wasinapaq kani",
      7: "サービス相談",
      8: "Consulta de serviço",
      9: "Consultation de service",
      10: "서비스 상담",
    },
    respuesta: {
      1: "Answer 1 for service inquiry",
      2: "Respuesta 1 para consulta de servicios",
      3: "服务咨询答案1",
      4: "Ответ 1 на запрос об услуге",
      5: "إجابة 1 لاستفسار الخدمة",
      6: "1 qanqa, jawqanqa wasi",
      7: "サービス相談の回答1",
      8: "resposta 1 para consulta de serviço",
      9: "réponse 1 pour la consultation de service",
      10: "서비스 문의에 대한 답변 1",
    },
  },
  {
    id: 4,
    categoria: {
      1: "Pre-sale Price",
      2: "Precio Preventa",
      3: "预售价格",
      4: "Цена предпродажи",
      5: "سعر البيع المسبق",
      6: "Qillqanapaqmi chaskisqa",
      7: "プリセール価格",
      8: "Preço de pré-venda",
      9: "Prix de prévente",
      10: "사전 판매 가격",
    },
    respuesta: {
      1: "Answer 1 for pre-sale price",
      2: "Respuesta 1 para Precio Preventa",
      3: "预售价格答案1",
      4: "Ответ 1 на предварительную цену",
      5: "إجابة 1 لسعر البيع المسبق",
      6: "1 qanqa, jawqanqa pre-sale",
      7: "プリセール価格の回答1",
      8: "resposta 1 para preço de pré-venda",
      9: "réponse 1 pour le prix de prévente",
      10: "사전 판매 가격에 대한 답변 1",
    },
  },
  {
    id: 5,
    categoria: {
      1: "Other Inquiries",
      2: "Otras consultas",
      3: "其他查询",
      4: "Другие запросы",
      5: "استفسارات أخرى",
      6: "Kaypi mana yachanichu",
      7: "その他のお問い合わせ",
      8: "Outras consultas",
      9: "Autres demandes",
      10: "기타 문의",
    },
    respuesta: {
      id: 1,
      1: "Answer 1 for other inquiries",
      2: "Respuesta 1 para otras consultas",
      3: "其他查询答案1",
      4: "Ответ 1 на другие запросы",
      5: "إجابة 1 للاستفسارات الأخرى",
      6: "1 qanqa, jawqanqa kaypi",
      7: "その他のお問い合わせの回答1",
      8: "resposta 1 para outras consultas",
      9: "réponse 1 pour d'autres demandes",
      10: "다른 문의에 대한 답변 1",
    },
  },
];

export const responseInit = [
  {
    id: 1,
    respuesta: {
      1: "Welcome to our company's chatbot! I'm here to provide you with information about our marketing and software development products and services. How can I assist you today?",
      2: "¡Bienvenido al chatbot de nuestra empresa! Estoy aquí para proporcionarte información sobre nuestros productos y servicios de marketing y desarrollo de software. ¿En qué puedo ayudarte hoy?",
      3: "欢迎使用我们公司的聊天机器人！我在这里为您提供有关我们的营销和软件开发产品以及服务的信息。我今天可以帮您什么忙？",
      4: "Добро пожаловать в чат-бот нашей компании! Я здесь, чтобы предоставить вам информацию о наших продуктах и услугах в области маркетинга и разработки программного обеспечения. Чем я могу помочь вам сегодня?",
      5: "مرحبًا بك في روبوت الدردشة لشركتنا! أنا هنا لتزويدك بمعلومات حول منتجاتنا وخدماتنا في مجال التسويق وتطوير البرمجيات. كيف يمكنني مساعدتك اليوم؟",
      6: "¡Kamisaraki kani maypi qillqanapaqmi! Kaypi ñuqaqaqa yanapaqmi yanapaqkunaqa yanapaqmi kani. ¿Ima sutiyki kani?",
      7: "当社のチャットボットへようこそ！私は、マーケティングとソフトウェア開発の製品やサービスに関する情報を提供するためにここにいます。今日はどのようにお手伝いできますか？",
      8: "Bem-vindo ao chatbot da nossa empresa! Estou aqui para fornecer informações sobre nossos produtos e serviços de marketing e desenvolvimento de software. Como posso ajudar você hoje?",
      9: "Bienvenue sur le chatbot de notre entreprise ! Je suis là pour vous fournir des informations sur nos produits et services en matière de marketing et de développement logiciel. Comment puis-je vous aider aujourd'hui ?",
      10: "저희 회사의 챗봇에 오신 것을 환영합니다! 저는 당신에게 마케팅 및 소프트웨어 개발 제품 및 서비스에 관한 정보를 제공하기 위해 여기 있습니다. 오늘은 어떻게 도움을 드릴까요?",
    },
  },
];
