export const category = [
  {
    id: 1,
    categoria: {
      1: "Issuance and Refund",
      2: "Emisión y reembolso",
      3: "发行和退款",
      4: "Выпуск и возврат",
      5: "الإصدار والاسترداد",
      6: "Sasachay hinaspa qullqi kutichiy",
      7: "発行と払い戻し",
      8: "Emissão e reembolso",
      9: "Émission et remboursement",
      10: "발행 및 환불",
    },
    respuesta: {
      1: "To issue a software license, visit our website and create an account. Then, select the product or service you want to purchase and follow the on-screen instructions. To request a refund, please contact our customer service team",
      2: "Para emitir una licencia de software, visite nuestro sitio web y cree una cuenta. Luego, seleccione el producto o servicio que desea comprar y siga las instrucciones en pantalla. Para solicitar un reembolso, comuníquese con nuestro equipo de servicio al cliente.",
      3: "要发行软件许可证，请访问我们的网站并创建帐户。然后，选择要购买的产品或服务，并按照屏幕上的说明操作。要请求退款，请联系我们的客户服务团队",
      4: "Чтобы получить лицензию на программное обеспечение, посетите наш веб-сайт и создайте учетную запись. Затем выберите продукт или услугу, которую вы хотите приобрести, и следуйте инструкциям на экране. Чтобы запросить возврат, пожалуйста, свяжитесь с нашей службой поддержки клиентов",
      5: "لإصدار ترخيص برنامج معين، قم بزيارة موقعنا على الإنترنت وأنشئ حسابًا. ثم اختر المنتج أو الخدمة التي تريد شرائها واتبع التعليمات الموجودة على الشاشة. لطلب استرداد الأموال، يرجى الاتصال بفريق خدمة العملاء لدينا",
      6: "Software licenciata qunaykipaq, web kitiykuman yaykuy chaymanta huk yupayta ruway. Chaymanta, rantiyta munasqayki ruruta utaq serviciota akllay chaymanta pantallapi kamachiykunata qatiy. Kutichiyta mañanaykipaq, ama hina kaspa yanapakuy equipoykuwan rimanakuy.",
      7: "ソフトウェアライセンスを発行するには、当社のWebサイトにアクセスしてアカウントを作成します。次に、購入したい製品またはサービスを選択し、画面の指示に従います。返金をリクエストするには、カスタマーサービスチームにお問い合わせください",
      8: "Para emitir uma licença de software, visite nosso site e crie uma conta. Em seguida, selecione o produto ou serviço que deseja comprar e siga as instruções na tela. Para solicitar um reembolso, entre em contato com nossa equipe de atendimento ao cliente",
      9: "Pour émettre une licence logicielle, visitez notre site Web et créez un compte. Ensuite, sélectionnez le produit ou le service que vous souhaitez acheter et suivez les instructions à l'écran. Pour demander un remboursement, veuillez contacter notre équipe de service client",
      10: "소프트웨어 라이선스를 발급하려면 웹 사이트를 방문하여 계정을 만듭니다. 그런 다음 구매하려는 제품 또는 서비스를 선택하고 화면의 지침을 따릅니다. 환불을 요청하려면 고객 서비스 팀에 문의하십시오",
    },
  },
  {
    id: 2,
    categoria: {
      1: "Pre-sale",
      2: "Preventa",
      3: "预售",
      4: "Предпродажа",
      5: "البيع المسبق",
      6: "Preventa",
      7: "プリセール",
      8: "Pré-venda",
      9: "Prévente",
      10: "사전 판매",
    },
    respuesta: {
      1: "Our company offers software for client, project and content management. We also provide technical support, training and consulting.",
      2: "Nuestra empresa ofrece software para gestión de clientes, proyectos y contenido. También brindamos soporte técnico, capacitación y consultoría.",
      3: "我们公司提供客户，项目和内容管理软件。我们还提供技术支持，培训和咨询。",
      4: "Наша компания предлагает программное обеспечение для управления клиентами, проектами и контентом. Мы также предоставляем техническую поддержку, обучение и консультации.",
      5: "تقدم شركتنا برامج لإدارة العملاء والمشاريع والمحتوى. نحن نقدم أيضًا الدعم الفني والتدريب والاستشارات.",
      6: "Empresayku software cliente, proyecto chaymanta contenido kamachiypaq qun. Hinallataqmi yanapakuy técnico, capacitación hinaspa consultoría nisqakunata quyku",
      7: "当社は、クライアント、プロジェクト、コンテンツ管理用のソフトウェアを提供しています。また、技術サポート、トレーニング、コンサルティングも提供しています。",
      8: "Nossa empresa oferece software para gerenciamento de clientes, projetos e conteúdo. Também fornecemos suporte técnico, treinamento e consultoria.",
      9: "Notre entreprise propose des logiciels de gestion de la clientèle, des projets et du contenu. Nous fournissons également un support technique, une formation et des conseils.",
      10: "저희 회사는 고객, 프로젝트 및 콘텐츠 관리를 위한 소프트웨어를 제공합니다. 또한 기술 지원, 교육 및 컨설팅을 제공합니다.",
    },
  },
  {
    id: 3,
    categoria: {
      1: "Service Inquiry",
      2: "Consulta de servicios",
      3: "服务咨询",
      4: "Консультация по услугам",
      5: "استشارة الخدمة",
      6: "Wasinapaq kani",
      7: "サービス相談",
      8: "Consulta de serviço",
      9: "Consultation de service",
      10: "서비스 상담",
    },
    respuesta: {
      1: "To open a support ticket, visit our website and create an account. Then, select the Technical Support option and follow the on-screen instructions.",
      2: "Para abrir un ticket de soporte técnico, visite nuestro sitio web y cree una cuenta. Luego, seleccione la opción Soporte técnico y siga las instrucciones en pantalla.",
      3: "要打开支持票证，请访问我们的网站并创建帐户。然后，选择“技术支持”选项并按照屏幕上的说明操作。",
      4: "Чтобы открыть техническую поддержку, посетите наш веб-сайт и создайте учетную запись. Затем выберите опцию «Техническая поддержка» и следуйте инструкциям на экране.",
      5: "لفتح تذكرة دعم فني، قم بزيارة موقعنا على الإنترنت وأنشئ حسابًا. ثم اختر خيار الدعم الفني واتبع التعليمات الموجودة على الشاشة.",
      6: "Yanapakuy boleto kichaypaq, web kitiykuman yaykuy chaymanta huk yupayta ruway. Chaymanta akllay Soporte Técnico nisqa akllanata hinaspa pantallapi kamachikuykunata qatipay",
      7: "サポートチケットを開くには、当社のWebサイトにアクセスしてアカウントを作成します。次に、[技術サポート]オプションを選択し、画面の指示に従います。",
      8: "Para abrir um ticket de suporte, visite nosso site e crie uma conta. Em seguida, selecione a opção Suporte técnico e siga as instruções na tela.",
      9: "Pour ouvrir un ticket de support, visitez notre site Web et créez un compte. Ensuite, sélectionnez l'option Support technique et suivez les instructions à l'écran.",
      10: "지원 티켓을 열려면 웹 사이트를 방문하여 계정을 만듭니다. 그런 다음 기술 지원 옵션을 선택하고 화면의 지침을 따릅니다.",
    },
  },
  {
    id: 4,
    categoria: {
      1: "Pre-sale Price",
      2: "Precio Preventa",
      3: "预售价格",
      4: "Цена предпродажи",
      5: "سعر البيع المسبق",
      6: "Qillqanapaqmi chaskisqa",
      7: "プリセール価格",
      8: "Preço de pré-venda",
      9: "Prix de prévente",
      10: "사전 판매 가격",
    },
    respuesta: {
      1: "The price depends on several factors. For a personalized quote, please contact our sales team.",
      2: "El precio depende de varios factores. Para obtener un presupuesto personalizado, comuníquese con nuestro equipo de ventas.",
      3: "价格取决于多种因素。有关个性化报价，请联系我们的销售团队。",
      4: "Цена зависит от нескольких факторов. Для индивидуального предложения свяжитесь с нашей командой продаж.",
      5: "السعر يعتمد على عدة عوامل. للحصول على عرض سعر مخصص ، يرجى الاتصال بفريق المبيعات لدينا.",
      6: "Chay precioqa askha factorkunamantan kanqa. Huk sapanchasqa cotización kaqpaq, ama hina kaspa rantiq equipoykuwan rimanakuy.",
      7: "価格は、いくつかの要因によって異なります。個別の見積もりについては、弊社の営業チームまでお問い合わせください。",
      8: "O preço depende de vários fatores. Para uma cotação personalizada, entre em contato com nossa equipe de vendas.",
      9: "Le prix dépend de plusieurs facteurs. Pour un devis personnalisé, veuillez contacter notre équipe commerciale.",
      10: "가격은 여러 요소에 따라 다릅니다. 맞춤 견적을 원하시면 판매 팀에 문의하십시오.",
    },
  },
  {
    id: 5,
    categoria: {
      1: "Other Inquiries",
      2: "Otras consultas",
      3: "其他查询",
      4: "Другие запросы",
      5: "استفسارات أخرى",
      6: "Huk tapuykuna",
      7: "その他のお問い合わせ",
      8: "Outras consultas",
      9: "Autres demandes",
      10: "기타 문의",
    },
    respuesta: {
      id: 1,
      1: "It seems that you want to make a more specialized consultation. Click this message to chat right now.",
      2: "Parece ser que deseas realizar una consulta más especializada. Haz clic en este mensaje para chatear ahora mismo.",
      3: "看来您想进行更专业的咨询。点击此消息立即聊天。",
      4: "Похоже, вы хотите задать более специализированный вопрос. Нажмите на это сообщение, чтобы начать чат прямо сейчас.",
      5: "يبدو أنك تريد إجراء استشارة أكثر تخصصًا. انقر فوق هذه الرسالة للدردشة الآن.",
      6: "Chayqa uyarikunmi huk consulta aswan especializada ruwayta munasqaykiman hina. Kay willakuyta ñit’iy kunanpacha rimanaykipaq",
      7: "より専門的な相談をしたいようです。このメッセージをクリックして今すぐチャットしてください。",
      8: "Parece que você deseja fazer uma consulta mais especializada. Clique nesta mensagem para conversar agora mesmo.",
      9: "Il semble que vous souhaitiez faire une consultation plus spécialisée. Cliquez sur ce message pour discuter dès maintenant.",
      10: "더 전문적인 상담을 원하는 것 같습니다. 지금 바로 채팅하려면이 메시지를 클릭하십시오.",
    },
    buttonToForm: {
      1: "Start chatting",
      2: "Comenzar a chatear",
      3: "开始聊天",
      4: "Начать чат",
      5: "ابدأ الدردشة",
      6: "rimayta qallariy",
      7: "チャットを開始する",
      8: "Iniciar chat",
      9: "Commencer à chatter",
      10: "채팅 시작",
    },
  },
];

export const responseInit = [
  {
    id: 1,
    respuesta: {
      1: "Welcome to our company's chatbot! I'm here to provide you with information about our marketing and software development products and services. How can I assist you today?",
      2: "¡Bienvenido al chatbot de nuestra empresa! Estoy aquí para proporcionarte información sobre nuestros productos y servicios de marketing y desarrollo de software. ¿En qué puedo ayudarte hoy?",
      3: "欢迎使用我们公司的聊天机器人！我在这里为您提供有关我们的营销和软件开发产品以及服务的信息。我今天可以帮您什么忙？",
      4: "Добро пожаловать в чат-бот нашей компании! Я здесь, чтобы предоставить вам информацию о наших продуктах и услугах в области маркетинга и разработки программного обеспечения. Чем я могу помочь вам сегодня?",
      5: "مرحبًا بك في روبوت الدردشة لشركتنا! أنا هنا لتزويدك بمعلومات حول منتجاتنا وخدماتنا في مجال التسويق وتطوير البرمجيات. كيف يمكنني مساعدتك اليوم؟",
      6: "¡Allin hamusqayki empresaykupa chatbot nisqaman! Kaypi kachkani software ruwayniykumanta chaymanta qhatuypaq rurukuna chaymanta yanapakuyniykumanta willayta qunaypaq. ¿Imaynatataq kunan punchaw yanapaykiman?",
      7: "当社のチャットボットへようこそ！私は、マーケティングとソフトウェア開発の製品やサービスに関する情報を提供するためにここにいます。今日はどのようにお手伝いできますか？",
      8: "Bem-vindo ao chatbot da nossa empresa! Estou aqui para fornecer informações sobre nossos produtos e serviços de marketing e desenvolvimento de software. Como posso ajudar você hoje?",
      9: "Bienvenue sur le chatbot de notre entreprise ! Je suis là pour vous fournir des informations sur nos produits et services en matière de marketing et de développement logiciel. Comment puis-je vous aider aujourd'hui ?",
      10: "저희 회사의 챗봇에 오신 것을 환영합니다! 저는 당신에게 마케팅 및 소프트웨어 개발 제품 및 서비스에 관한 정보를 제공하기 위해 여기 있습니다. 오늘은 어떻게 도움을 드릴까요?",
    },
  },
];

export const formTo2Cap = [
  {
    id: 1,
    titleForm: {
      1: "Contact us",
      2: "Comunícate con nosotros",
      3: "联系我们",
      4: "Свяжитесь с нами",
      5: "اتصل بنا",
      6: "Ñoqaykuwan rimanakuy",
      7: "お問い合わせ",
      8: "Entre em contato conosco",
      9: "Contactez-nous",
      10: "문의하기",
    },

    form: {
      id: 1,
      fullaname: {
        1: "Full name",
        2: "Nombre completo",
        3: "全名",
        4: "Полное имя",
        5: "الاسم الكامل",
        6: "Lliw suti",
        7: "フルネーム",
        8: "Nome completo",
        9: "Nom complet",
        10: "전체 이름",
      },
      email: {
        1: "Email",
        2: "Correo electrónico",
        3: "电子邮件",
        4: "Электронная почта",
        5: "البريد الإلكتروني",
        6: "Email",
        7: "Eメール",
        8: "O email",
        9: "Email",
        10: "이메일",
      },
      phone: {
        1: "Phone",
        2: "Teléfono",
        3: "电话",
        4: "Телефон",
        5: "هاتف",
        6: "Rinri",
        7: "電話",
        8: "Telefone",
        9: "Téléphone",
        10: "전화",
      },
      consult: {
        1: "Consult",
        2: "Consulta",
        3: "查询",
        4: "Запрос",
        5: "استفسار",
        6: "Tapukuy",
        7: "相談",
        8: "Consulta",
        9: "Consultation",
        10: "문의",
      },
      optionSend: {
        1: "Send",
        2: "Enviar",
        3: "发送",
        4: "Отправить",
        5: "إرسال",
        6: "Apachiy",
        7: "送信",
        8: "Enviar",
        9: "Envoyer",
        10: "보내다",
      },
      optionCancel: {
        1: "Cancel",
        2: "Cancelar",
        3: "取消",
        4: "Отмена",
        5: "إلغاء",
        6: "Sayachiy",
        7: "キャンセル",
        8: "Cancelar",
        9: "Annuler",
        10: "취소",
      },
      comboBoxArea: {
        labelComboBox: {
          1: "Area / Process",
          2: "Área / Proceso",
          3: "区域/流程",
          4: "Область / Процесс",
          5: "المنطقة / العملية",
          6: "Área / Proceso",
          7: "エリア/プロセス",
          8: "Área / Processo",
          9: "Zone / Processus",
          10: "지역 / 프로세스",
        },
        option1: {
          1: "Web Analytics",
          2: "Analítica Web",
          3: "网络分析",
          4: "Веб-аналитика",
          5: "تحليلات الويب",
          6: "Analítica Web",
          7: "ウェブ解析",
          8: "Análise da Web",
          9: "Analyse Web",
          10: "웹 분석",
        },
        option2: {
          1: "Email Marketing",
          2: "Email Marketing",
          3: "电子邮件营销",
          4: "Электронная почта Маркетинг",
          5: "التسويق عبر البريد الإلكتروني",
          6: "Email Marketing",
          7: "電子メールマーケティング",
          8: "Marketing por e-mail",
          9: "Marketing par e-mail",
          10: "이메일 마케팅",
        },
        option3: {
          1: "SEO",
          2: "SEO",
          3: "搜索引擎优化",
          4: "Поисковая оптимизация",
          5: "تحسين محركات البحث",
          6: "SEO",
          7: "SEO",
          8: "SEO",
          9: "SEO",
          10: "SEO",
        },
        option4: {
          1: "Social networks",
          2: "Redes sociales",
          3: "社交网络",
          4: "Социальные сети",
          5: "شبكات التواصل الاجتماعي",
          6: "Redes sociales",
          7: "ソーシャルネットワーク",
          8: "Redes sociais",
          9: "Réseaux sociaux",
          10: "소셜 네트워크",
        },
        option5: {
          1: "Online advertising",
          2: "Publicidad online",
          3: "在线广告",
          4: "Интернет-реклама",
          5: "الإعلان عبر الإنترنت",
          6: "Publicidad online",
          7: "オンライン広告",
          8: "Publicidade online",
          9: "Publicité en ligne",
          10: "온라인 광고",
        },
        option6: {
          1: "Content Marketing",
          2: "Marketing de contenidos",
          3: "内容营销",
          4: "Маркетинг контента",
          5: "تسويق المحتوى",
          6: "Marketing de contenidos",
          7: "コンテンツマーケティング",
          8: "Marketing de conteúdo",
          9: "Marketing de contenu",
          10: "콘텐츠 마케팅",
        },
      },
    },
  },
];

export const textModal = [
  {
    id: 1,
    textModalClose: {
      1: "END CHAT",
      2: "FINALIZAR CHAT",
      3: "结束聊天",
      4: "ЗАКОНЧИТЬ ЧАТ",
      5: "إنهاء الدردشة",
      6: "KAMISARAKI KANI",
      7: "チャットを終了する",
      8: "FINALIZAR CHAT",
      9: "FIN DU CHAT",
      10: "채팅 종료",
    },
    textModal3Cap: {
      1: "CHAT WITH AN ADVISOR",
      2: "CHATEA CON UN ASESOR",
      3: "与顾问聊天",
      4: "ЧАТ С КОНСУЛЬТАНТОМ",
      5: "الدردشة مع مستشار",
      6: "CHAT CON UN CONSEJOR",
      7: "アドバイザーとチャット",
      8: "CONVERSE COM UM CONSULTOR",
      9: "DISCUTER AVEC UN CONSEILLER",
      10: "고문과 채팅",
    },
  },
];

export const chatDataCaps = [
  {
    labelTextField: {
      1: "Write a message",
      2: "Escribe un mensaje",
      3: "写信息",
      4: "Написать сообщение",
      5: "اكتب رسالة",
      6: "Kachkani willakuy",
      7: "メッセージを書く",
      8: "Escreva uma mensagem",
      9: "Écrivez un message",
      10: "메시지를 쓰다",
    },
    toastMessage: {
      1: "Message removed for security reasons",
      2: "Mensaje eliminado por motivos de seguridad",
      3: "出于安全原因而删除的消息",
      4: "Сообщение удалено по соображениям безопасности",
      5: "تمت إزالة الرسالة لأسباب أمنية",
      6: "Seguridadpaqmi chay willakuyta qullqiy",
      7: "セキュリティ上の理由によりメッセージが削除されました",
      8: "Mensagem removida por motivos de segurança",
      9: "Message supprimé pour des raisons de sécurité",
      10: "보안상의 이유로 메시지가 삭제되었습니다",
    },
  },
];
